[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SpannHTML"
version = "1.0.0"
authors = [
  {name="Zhou C."},
]
description = "Interactive spatial viewer and cluster correction for AnnData in a single HTML file"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.22,<2.0",
    "pandas>=1.5,<3.0",
    "anndata>=0.8.0,<0.12",
    "plotly>=5.10,<7.0"
]

[project.urls]
"Homepage" = "https://github.com/Zhouc02/SpannHTML"
"Bug Tracker" = "https://github.com/Zhouc02/SpannHTML/issues"
